services:
  postgres:
    image: postgres:16-alpine
    container_name: chatspark-postgres
    ports:
      - "5432:5432"
    networks:
      - chatspark-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatSpark_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  
  redis:
    image: redis:7-alpine
    container_name: chatspark-redis
    ports:
      - "6379:6379"
    networks:
      - chatspark-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chatspark-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - chatspark-net
    environment:
      RABBITMQ_DEFAULT_USER: chatspark
      RABBITMQ_DEFAULT_PASS: chatspark_dev
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatspark-api
    ports:
      - "8080:8080"
    networks:
      - chatspark-net
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  


networks:
  chatspark-net:
    driver: bridge


volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
      
      
